+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Tue Aug 29 14:49:13 2023 - INFO  - Start environment preparation.
+ mapfile -t point_list
++ CREATE_FS
++ fs_type='ext3 ext4 xfs'
+++ date +%Y%m%d%H%M%S
++ cur_date=20230829144913
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230829144913
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vda
+++ disk_name=/dev/vda
+++ pvcreate /dev/vda -f
+++ [[ 127 -eq 0 ]]
++++ pvcreate /dev/vda
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230829144913
++ point=/tmp/point120230829144913
++ lvcreate -n test_lv120230829144913 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext3 /dev//test_lv120230829144913
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv120230829144913 does not exist and no size was specified.
++ mkdir /tmp/point120230829144913
++ mount /dev//test_lv120230829144913 /tmp/point120230829144913
mount: /tmp/point120230829144913: special device /dev//test_lv120230829144913 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230829144913 '
++ count=2
++ for fs in ${fs_type[@]}
++ lvname=test_lv220230829144913
++ point=/tmp/point220230829144913
++ lvcreate -n test_lv220230829144913 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext4 /dev//test_lv220230829144913
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv220230829144913 does not exist and no size was specified.
++ mkdir /tmp/point220230829144913
++ mount /dev//test_lv220230829144913 /tmp/point220230829144913
mount: /tmp/point220230829144913: special device /dev//test_lv220230829144913 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230829144913 /tmp/point220230829144913 '
++ count=3
++ for fs in ${fs_type[@]}
++ lvname=test_lv320230829144913
++ point=/tmp/point320230829144913
++ lvcreate -n test_lv320230829144913 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t xfs /dev//test_lv320230829144913
mkfs: failed to execute mkfs.xfs: No such file or directory
++ mkdir /tmp/point320230829144913
++ mount /dev//test_lv320230829144913 /tmp/point320230829144913
mount: /tmp/point320230829144913: special device /dev//test_lv320230829144913 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230829144913 /tmp/point220230829144913 /tmp/point320230829144913 '
++ count=4
++ echo /tmp/point120230829144913 /tmp/point220230829144913 /tmp/point320230829144913
++ echo '/tmp/point120230829144913 /tmp/point220230829144913 /tmp/point320230829144913'
++ awk '{print $2}'
+ ext3_point=/tmp/point220230829144913
++ echo '/tmp/point120230829144913 /tmp/point220230829144913 /tmp/point320230829144913'
++ awk '{print $3}'
+ ext4_point=/tmp/point320230829144913
++ echo '/tmp/point120230829144913 /tmp/point220230829144913 /tmp/point320230829144913'
++ awk '{print $4}'
+ xfs_point=
+ echo 'test ext3'
+ ln /tmp/point220230829144913/testFile /tmp/point220230829144913/testLink
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Aug 29 14:49:13 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Aug 29 14:49:13 2023 - INFO  - Start to run test.
++ cut -d : -f 3
++ stat /tmp/point220230829144913/testLink
++ awk '{print $1}'
++ grep Inode
+ ori_inode=9779
+ mv /tmp/point220230829144913/testLink /tmp/point220230829144913/testLink1
++ stat /tmp/point220230829144913/testLink1
++ grep Inode
++ cut -d : -f 3
++ awk '{print $1}'
+ inode1=9779
+ [[ 9779 == \9\7\7\9 ]]
+ CHECK_RESULT 0 0 0 'The hard link inode is changed unexpectly when mv on ext3'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The hard link inode is changed unexpectly when mv on ext3'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /tmp/point220230829144913/testLink1 /tmp/point320230829144913/testLink
++ stat /tmp/point320230829144913/testLink
++ grep Inode
++ cut -d : -f 3
++ awk '{print $1}'
+ inode2=9779
+ [[ 9779x == \9\7\7\9x ]]
+ CHECK_RESULT 0 0 0 'The hard link inode change when mv from ext3 to ext4'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The hard link inode change when mv from ext3 to ext4'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /tmp/point320230829144913/testLink /testLink
++ stat /testLink
++ grep Inode
++ cut -d : -f 3
++ awk '{print $1}'
+ inode3=22
+ [[ 9779x != \2\2x ]]
+ CHECK_RESULT 0 0 0 'The hard link inode doesn'\''t change when mv from ext3 to xfs'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The hard link inode doesn'\''t change when mv from ext3 to xfs'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Aug 29 14:49:13 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Tue Aug 29 14:49:13 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Aug 29 14:49:13 2023 - INFO  - Start to restore the test environment.
+ list='/tmp/point120230829144913 /tmp/point220230829144913 /tmp/point320230829144913'
+ REMOVE_FS '/tmp/point120230829144913 /tmp/point220230829144913 /tmp/point320230829144913'
+ point_list=($1)
++ seq 0 2
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230829144913
++ grep /tmp/point120230829144913
++ df -T
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point220230829144913
++ df -T
++ grep /tmp/point220230829144913
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point320230829144913
++ df -T
++ awk '{print $1}'
++ grep /tmp/point320230829144913
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Aug 29 14:49:13 2023 - INFO  - End to restore the test environment.
