+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Aug 31 03:36:17 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL iputils
+ pkgs=iputils
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs iputils --node 1 --tempfile ''
Thu Aug 31 03:36:27 2023 - INFO  - pkgs:(iputils) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Thu Aug 31 03:36:27 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Aug 31 03:36:28 2023 - INFO  - Start to run test.
+ tracepath -V
+ grep 'tracepath from iputils'
tracepath from iputils 20221126
+ CHECK_RESULT 0 0 0 'tracepath -V execute failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='tracepath -V execute failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep pmtu
+ tracepath -4 ''
tracepath: : Name or service not known
+ CHECK_RESULT 1 0 0 'tracepath -4 execute failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='tracepath -4 execute failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'tracepath -4 execute failed'
+ LOG_ERROR 'tracepath -4 execute failed'
+ message='tracepath -4 execute failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'tracepath -4 execute failed'
Thu Aug 31 03:36:29 2023 - ERROR - tracepath -4 execute failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iputils_tracepath.sh line 33'
+ message='oe_test_iputils_tracepath.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iputils_tracepath.sh line 33'
Thu Aug 31 03:36:30 2023 - ERROR - oe_test_iputils_tracepath.sh line 33
+ return 0
+ tracepath -6 ''
+ grep pmtu
tracepath: : Name or service not known
+ CHECK_RESULT 1 0 0 'tracepath -6 execute failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='tracepath -6 execute failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'tracepath -6 execute failed'
+ LOG_ERROR 'tracepath -6 execute failed'
+ message='tracepath -6 execute failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'tracepath -6 execute failed'
Thu Aug 31 03:36:30 2023 - ERROR - tracepath -6 execute failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iputils_tracepath.sh line 35'
+ message='oe_test_iputils_tracepath.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iputils_tracepath.sh line 35'
Thu Aug 31 03:36:31 2023 - ERROR - oe_test_iputils_tracepath.sh line 35
+ return 0
+ tracepath -b ''
+ grep pmtu
tracepath: : Name or service not known
+ CHECK_RESULT 1 0 0 'tracepath -b execute failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='tracepath -b execute failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'tracepath -b execute failed'
+ LOG_ERROR 'tracepath -b execute failed'
+ message='tracepath -b execute failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'tracepath -b execute failed'
Thu Aug 31 03:36:32 2023 - ERROR - tracepath -b execute failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iputils_tracepath.sh line 37'
+ message='oe_test_iputils_tracepath.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iputils_tracepath.sh line 37'
Thu Aug 31 03:36:32 2023 - ERROR - oe_test_iputils_tracepath.sh line 37
+ return 0
+ tracepath -l 65534 ''
+ grep pmtu
tracepath: : Name or service not known
+ CHECK_RESULT 1 0 0 'tracepath -l execute failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='tracepath -l execute failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'tracepath -l execute failed'
+ LOG_ERROR 'tracepath -l execute failed'
+ message='tracepath -l execute failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'tracepath -l execute failed'
Thu Aug 31 03:36:33 2023 - ERROR - tracepath -l execute failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iputils_tracepath.sh line 39'
+ message='oe_test_iputils_tracepath.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iputils_tracepath.sh line 39'
Thu Aug 31 03:36:34 2023 - ERROR - oe_test_iputils_tracepath.sh line 39
+ return 0
+ grep pmtu
+ tracepath -m 10 ''
tracepath: : Name or service not known
+ CHECK_RESULT 1 0 0 'tracepath -m execute failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='tracepath -m execute failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'tracepath -m execute failed'
+ LOG_ERROR 'tracepath -m execute failed'
+ message='tracepath -m execute failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'tracepath -m execute failed'
Thu Aug 31 03:36:35 2023 - ERROR - tracepath -m execute failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iputils_tracepath.sh line 41'
+ message='oe_test_iputils_tracepath.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iputils_tracepath.sh line 41'
Thu Aug 31 03:36:35 2023 - ERROR - oe_test_iputils_tracepath.sh line 41
+ return 0
+ grep pmtu
+ tracepath -n ''
tracepath: : Name or service not known
+ CHECK_RESULT 1 0 0 'tracepath -n execute failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='tracepath -n execute failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'tracepath -n execute failed'
+ LOG_ERROR 'tracepath -n execute failed'
+ message='tracepath -n execute failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'tracepath -n execute failed'
Thu Aug 31 03:36:36 2023 - ERROR - tracepath -n execute failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iputils_tracepath.sh line 43'
+ message='oe_test_iputils_tracepath.sh line 43'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iputils_tracepath.sh line 43'
Thu Aug 31 03:36:37 2023 - ERROR - oe_test_iputils_tracepath.sh line 43
+ return 0
+ tracepath -p 15 ''
+ grep pmtu
tracepath: : Name or service not known
+ CHECK_RESULT 1 0 0 'tracepath -p execute failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='tracepath -p execute failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'tracepath -p execute failed'
+ LOG_ERROR 'tracepath -p execute failed'
+ message='tracepath -p execute failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'tracepath -p execute failed'
Thu Aug 31 03:36:37 2023 - ERROR - tracepath -p execute failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iputils_tracepath.sh line 45'
+ message='oe_test_iputils_tracepath.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iputils_tracepath.sh line 45'
Thu Aug 31 03:36:38 2023 - ERROR - oe_test_iputils_tracepath.sh line 45
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Aug 31 03:36:39 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Aug 31 03:36:39 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'start to restore the test environment.'
+ message='start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start to restore the test environment.'
Thu Aug 31 03:36:40 2023 - INFO  - start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Aug 31 03:36:40 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Aug 31 03:36:41 2023 - INFO  - End to restore the test environment.
