+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Tue Aug 29 10:15:10 2023 - INFO  - Start to prepare the database config.
++ TEST_DISK 2
++ id=2
++ python3 /root/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 2
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/get_test_device.py", line 127, in <module>
    print(get_test_disk(args.node))
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/get_test_device.py", line 98, in get_test_disk
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ test_disk=/dev/
+ ssh_cmd_node 'cp /etc/fstab /etc/fstab.bak'
+ cmd='cp /etc/fstab /etc/fstab.bak'
+ SSH_CMD 'cp /etc/fstab /etc/fstab.bak' '' '' ''
+ cmd='cp /etc/fstab /etc/fstab.bak'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'cp /etc/fstab /etc/fstab.bak' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'fdisk /dev/ << diskEof
n
p
1

+100M
n
p
2

+100M
n
p
3

+100M
w
diskEof'
+ cmd='fdisk /dev/ << diskEof
n
p
1

+100M
n
p
2

+100M
n
p
3

+100M
w
diskEof'
+ SSH_CMD 'fdisk /dev/ << diskEof
n
p
1

+100M
n
p
2

+100M
n
p
3

+100M
w
diskEof' '' '' ''
+ cmd='fdisk /dev/ << diskEof
n
p
1

+100M
n
p
2

+100M
n
p
3

+100M
w
diskEof'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'fdisk /dev/ << diskEof
n
p
1

+100M
n
p
2

+100M
n
p
3

+100M
w
diskEof' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mkfs.ext3 /dev/1'
+ cmd='mkfs.ext3 /dev/1'
+ SSH_CMD 'mkfs.ext3 /dev/1' '' '' ''
+ cmd='mkfs.ext3 /dev/1'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'mkfs.ext3 /dev/1' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mkfs.ext4 /dev/2'
+ cmd='mkfs.ext4 /dev/2'
+ SSH_CMD 'mkfs.ext4 /dev/2' '' '' ''
+ cmd='mkfs.ext4 /dev/2'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'mkfs.ext4 /dev/2' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mkfs.xfs /dev/3'
+ cmd='mkfs.xfs /dev/3'
+ SSH_CMD 'mkfs.xfs /dev/3' '' '' ''
+ cmd='mkfs.xfs /dev/3'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'mkfs.xfs /dev/3' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mkdir /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ cmd='mkdir /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ SSH_CMD 'mkdir /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs' '' '' ''
+ cmd='mkdir /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'mkdir /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mount /dev/1 /mnt/test_ext3'
+ cmd='mount /dev/1 /mnt/test_ext3'
+ SSH_CMD 'mount /dev/1 /mnt/test_ext3' '' '' ''
+ cmd='mount /dev/1 /mnt/test_ext3'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'mount /dev/1 /mnt/test_ext3' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mount /dev/2 /mnt/test_ext4'
+ cmd='mount /dev/2 /mnt/test_ext4'
+ SSH_CMD 'mount /dev/2 /mnt/test_ext4' '' '' ''
+ cmd='mount /dev/2 /mnt/test_ext4'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'mount /dev/2 /mnt/test_ext4' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mount /dev/3 /mnt/test_xfs'
+ cmd='mount /dev/3 /mnt/test_xfs'
+ SSH_CMD 'mount /dev/3 /mnt/test_xfs' '' '' ''
+ cmd='mount /dev/3 /mnt/test_xfs'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'mount /dev/3 /mnt/test_xfs' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Tue Aug 29 10:15:11 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Aug 29 10:15:11 2023 - INFO  - Start to run test.
+ ssh_cmd_node 'df -iT | grep '\''/dev/*'\'''
+ cmd='df -iT | grep '\''/dev/*'\'''
+ SSH_CMD 'df -iT | grep '\''/dev/*'\''' '' '' ''
+ cmd='df -iT | grep '\''/dev/*'\'''
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'df -iT | grep '\''/dev/*'\''' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 0 'Check fs is mounted failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fs is mounted failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fs is mounted failed.'
+ LOG_ERROR 'Check fs is mounted failed.'
+ message='Check fs is mounted failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check fs is mounted failed.'
Tue Aug 29 10:15:11 2023 - ERROR - Check fs is mounted failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_automount.sh line 57'
+ message='oe_test_FSIO_mount_automount.sh line 57'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_automount.sh line 57'
Tue Aug 29 10:15:11 2023 - ERROR - oe_test_FSIO_mount_automount.sh line 57
+ return 0
+ ssh_cmd_node 'echo '\''/dev/1 /mnt/test_ext3 ext3 defaults 0 0'\'' >> /etc/fstab'
+ cmd='echo '\''/dev/1 /mnt/test_ext3 ext3 defaults 0 0'\'' >> /etc/fstab'
+ SSH_CMD 'echo '\''/dev/1 /mnt/test_ext3 ext3 defaults 0 0'\'' >> /etc/fstab' '' '' ''
+ cmd='echo '\''/dev/1 /mnt/test_ext3 ext3 defaults 0 0'\'' >> /etc/fstab'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'echo '\''/dev/1 /mnt/test_ext3 ext3 defaults 0 0'\'' >> /etc/fstab' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'echo '\''/dev/2 /mnt/test_ext4 ext4 defaults 0 0'\'' >> /etc/fstab'
+ cmd='echo '\''/dev/2 /mnt/test_ext4 ext4 defaults 0 0'\'' >> /etc/fstab'
+ SSH_CMD 'echo '\''/dev/2 /mnt/test_ext4 ext4 defaults 0 0'\'' >> /etc/fstab' '' '' ''
+ cmd='echo '\''/dev/2 /mnt/test_ext4 ext4 defaults 0 0'\'' >> /etc/fstab'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'echo '\''/dev/2 /mnt/test_ext4 ext4 defaults 0 0'\'' >> /etc/fstab' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'echo '\''/dev/3 /mnt/test_xfs xfs defaults 0 0'\'' >> /etc/fstab'
+ cmd='echo '\''/dev/3 /mnt/test_xfs xfs defaults 0 0'\'' >> /etc/fstab'
+ SSH_CMD 'echo '\''/dev/3 /mnt/test_xfs xfs defaults 0 0'\'' >> /etc/fstab' '' '' ''
+ cmd='echo '\''/dev/3 /mnt/test_xfs xfs defaults 0 0'\'' >> /etc/fstab'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'echo '\''/dev/3 /mnt/test_xfs xfs defaults 0 0'\'' >> /etc/fstab' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ REMOTE_REBOOT 2
+ node=2
+ waittime=
+ '[' x '!=' x ']'
+ python3 /root/mugen-riscv/libs/locallibs/remote_reboot.py reboot --node 2
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/remote_reboot.py", line 128, in <module>
    remote_reboot(args.node, args.waittime)
  File "/root/mugen-riscv/libs/locallibs/remote_reboot.py", line 100, in remote_reboot
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ REMOTE_REBOOT_WAIT 2
+ node=2
+ waittime=
+ '[' x '!=' x ']'
+ python3 /root/mugen-riscv/libs/locallibs/remote_reboot.py wait --node 2
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/remote_reboot.py", line 126, in <module>
    sys.exit(reboot_wait(args.node, args.waittime))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/remote_reboot.py", line 55, in reboot_wait
    elif machine_type.lower() == "kvm":
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
+ ssh_cmd_node 'df -iT | grep '\''/dev/*'\'''
+ cmd='df -iT | grep '\''/dev/*'\'''
+ SSH_CMD 'df -iT | grep '\''/dev/*'\''' '' '' ''
+ cmd='df -iT | grep '\''/dev/*'\'''
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'df -iT | grep '\''/dev/*'\''' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 0 'Check fs is mounted failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fs is mounted failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fs is mounted failed.'
+ LOG_ERROR 'Check fs is mounted failed.'
+ message='Check fs is mounted failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check fs is mounted failed.'
Tue Aug 29 10:15:11 2023 - ERROR - Check fs is mounted failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_automount.sh line 64'
+ message='oe_test_FSIO_mount_automount.sh line 64'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_automount.sh line 64'
Tue Aug 29 10:15:11 2023 - ERROR - oe_test_FSIO_mount_automount.sh line 64
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Aug 29 10:15:11 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug 29 10:15:11 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Aug 29 10:15:11 2023 - INFO  - Start to restore the test environment.
+ ssh_cmd_node 'umount /dev/1 /dev/2 /dev/3'
+ cmd='umount /dev/1 /dev/2 /dev/3'
+ SSH_CMD 'umount /dev/1 /dev/2 /dev/3' '' '' ''
+ cmd='umount /dev/1 /dev/2 /dev/3'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'umount /dev/1 /dev/2 /dev/3' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mv -f /etc/fstab.bak /etc/fstab'
+ cmd='mv -f /etc/fstab.bak /etc/fstab'
+ SSH_CMD 'mv -f /etc/fstab.bak /etc/fstab' '' '' ''
+ cmd='mv -f /etc/fstab.bak /etc/fstab'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'mv -f /etc/fstab.bak /etc/fstab' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'umount /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ cmd='umount /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ SSH_CMD 'umount /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs' '' '' ''
+ cmd='umount /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'umount /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'rm -rf /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ cmd='rm -rf /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ SSH_CMD 'rm -rf /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs' '' '' ''
+ cmd='rm -rf /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'rm -rf /mnt/test_ext3 /mnt/test_ext4 /mnt/test_xfs' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'fdisk /dev/ << diskEof
d

d

d

w
diskEof'
+ cmd='fdisk /dev/ << diskEof
d

d

d

w
diskEof'
+ SSH_CMD 'fdisk /dev/ << diskEof
d

d

d

w
diskEof' '' '' ''
+ cmd='fdisk /dev/ << diskEof
d

d

d

w
diskEof'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'fdisk /dev/ << diskEof
d

d

d

w
diskEof' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Aug 29 10:15:11 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ REMOTE_REBOOT 2
+ node=2
+ waittime=
+ '[' x '!=' x ']'
+ python3 /root/mugen-riscv/libs/locallibs/remote_reboot.py reboot --node 2
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/remote_reboot.py", line 128, in <module>
    remote_reboot(args.node, args.waittime)
  File "/root/mugen-riscv/libs/locallibs/remote_reboot.py", line 100, in remote_reboot
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ REMOTE_REBOOT_WAIT 2
+ node=2
+ waittime=
+ '[' x '!=' x ']'
+ python3 /root/mugen-riscv/libs/locallibs/remote_reboot.py wait --node 2
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/remote_reboot.py", line 126, in <module>
    sys.exit(reboot_wait(args.node, args.waittime))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/remote_reboot.py", line 55, in reboot_wait
    elif machine_type.lower() == "kvm":
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Aug 29 10:15:11 2023 - INFO  - End to restore the test environment.
