+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start loading data!'
+ message='Start loading data!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start loading data!'
Wed Aug 30 02:32:20 2023 - INFO  - Start loading data!
++ TEST_DISK 1
++ id=1
++ python3 /root/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ TEST_DISK=/dev/sr0
+ LOG_INFO 'Loading data is complete!'
+ message='Loading data is complete!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Loading data is complete!'
Wed Aug 30 02:32:21 2023 - INFO  - Loading data is complete!
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Aug 30 02:32:21 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'tang clevis clevis-dracut cryptsetup-reencrypt clevis-udisks2'
+ pkgs='tang clevis clevis-dracut cryptsetup-reencrypt clevis-udisks2'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'tang clevis clevis-dracut cryptsetup-reencrypt clevis-udisks2' --node 1 --tempfile ''
Wed Aug 30 02:32:21 2023 - ERROR - pkgs:(cryptsetup-reencrypt) not found
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ DNF_INSTALL tang 2
+ pkgs=tang
+ node=2
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs tang --node 2 --tempfile ''
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 176, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ fdisk /dev/sr0
+ echo -e 'n\n\np\n\n\n+100M\nw'
fdisk: cannot open /dev/sr0: No medium found

Welcome to fdisk (util-linux 2.39.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

+ ls /mnt/test_encrypted
+ rm -rf /mnt/test_encrypted
+ mkdir /mnt/test_encrypted
+ ls /etc/systemd/system/tangd.socket.d
ls: cannot access '/etc/systemd/system/tangd.socket.d': No such file or directory
+ SOCKET_CONTENT='[Socket]\nListenStream=\nListenStream=8009'
+ mkdir /etc/systemd/system/tangd.socket.d
+ echo -e '[Socket]\nListenStream=\nListenStream=8009'
++ uuidgen
+ UUID=f09f31c0-7ebb-4d87-884c-8af053b6425d
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Aug 30 02:32:21 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Wed Aug 30 02:32:21 2023 - INFO  - Start executing testcase.
+ echo -e '\n\n'
+ cryptsetup-reencrypt --type luks1 --new --reduce-device-size 8M /dev/sr01
oe_test_high_nbde.sh: line 44: cryptsetup-reencrypt: command not found
+ CHECK_RESULT 127 0 0 'Disk encryption failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Disk encryption failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Disk encryption failed'
+ LOG_ERROR 'Disk encryption failed'
+ message='Disk encryption failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Disk encryption failed'
Wed Aug 30 02:32:21 2023 - ERROR - Disk encryption failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 45'
+ message='oe_test_high_nbde.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 45'
Wed Aug 30 02:32:21 2023 - ERROR - oe_test_high_nbde.sh line 45
+ return 0
+ echo -e '\n'
+ cryptsetup open /dev/sr01 test_encrypted
oe_test_high_nbde.sh: line 46: cryptsetup: command not found
+ CHECK_RESULT 127 0 0 'Disk mapping failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Disk mapping failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Disk mapping failed'
+ LOG_ERROR 'Disk mapping failed'
+ message='Disk mapping failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Disk mapping failed'
Wed Aug 30 02:32:21 2023 - ERROR - Disk mapping failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 47'
+ message='oe_test_high_nbde.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 47'
Wed Aug 30 02:32:21 2023 - ERROR - oe_test_high_nbde.sh line 47
+ return 0
+ mkfs.ext4 /dev/mapper/test_encrypted -F
mke2fs 1.47.0 (5-Feb-2023)
The file /dev/mapper/test_encrypted does not exist and no size was specified.
+ mount /dev/mapper/test_encrypted /mnt/test_encrypted
mount: /mnt/test_encrypted: special device /dev/mapper/test_encrypted does not exist.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32 0 0 'Disk mount failed'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='Disk mount failed'
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'Disk mount failed'
+ LOG_ERROR 'Disk mount failed'
+ message='Disk mount failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Disk mount failed'
Wed Aug 30 02:32:21 2023 - ERROR - Disk mount failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 50'
+ message='oe_test_high_nbde.sh line 50'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 50'
Wed Aug 30 02:32:21 2023 - ERROR - oe_test_high_nbde.sh line 50
+ return 0
+ cryptsetup luksHeaderBackup /dev/sr01 --header-backup-file /tmp/header.bin
oe_test_high_nbde.sh: line 51: cryptsetup: command not found
+ CHECK_RESULT 127 0 0 'Backup luksHeader information failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Backup luksHeader information failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Backup luksHeader information failed'
+ LOG_ERROR 'Backup luksHeader information failed'
+ message='Backup luksHeader information failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Backup luksHeader information failed'
Wed Aug 30 02:32:21 2023 - ERROR - Backup luksHeader information failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 52'
+ message='oe_test_high_nbde.sh line 52'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 52'
Wed Aug 30 02:32:21 2023 - ERROR - oe_test_high_nbde.sh line 52
+ return 0
+ SLEEP_WAIT 2
+ wait_time=2
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 2 --cmd '' --mode 1
+ systemctl enable tangd.socket
Failed to enable unit: Unit file tangd.socket does not exist.
+ CHECK_RESULT 1 0 0 'Failed to enable tangd.socket service'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to enable tangd.socket service'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to enable tangd.socket service'
+ LOG_ERROR 'Failed to enable tangd.socket service'
+ message='Failed to enable tangd.socket service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to enable tangd.socket service'
Wed Aug 30 02:32:24 2023 - ERROR - Failed to enable tangd.socket service
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 55'
+ message='oe_test_high_nbde.sh line 55'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 55'
Wed Aug 30 02:32:24 2023 - ERROR - oe_test_high_nbde.sh line 55
+ return 0
+ systemctl daemon-reload
+ systemctl show tangd.socket -p Listen
+ grep 8009
+ CHECK_RESULT 1 0 0 'Failed to display the '\''Listen'\'' property of tangd.socket'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to display the '\''Listen'\'' property of tangd.socket'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to display the '\''Listen'\'' property of tangd.socket'
+ LOG_ERROR 'Failed to display the '\''Listen'\'' property of tangd.socket'
+ message='Failed to display the '\''Listen'\'' property of tangd.socket'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to display the '\''Listen'\'' property of tangd.socket'
Wed Aug 30 02:32:24 2023 - ERROR - Failed to display the 'Listen' property of tangd.socket
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 58'
+ message='oe_test_high_nbde.sh line 58'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 58'
Wed Aug 30 02:32:24 2023 - ERROR - oe_test_high_nbde.sh line 58
+ return 0
+ systemctl start tangd.socket
Failed to start tangd.socket: Unit tangd.socket not found.
+ CHECK_RESULT 5 0 0 'Failed to start tangd.socket service'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='Failed to start tangd.socket service'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'Failed to start tangd.socket service'
+ LOG_ERROR 'Failed to start tangd.socket service'
+ message='Failed to start tangd.socket service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to start tangd.socket service'
Wed Aug 30 02:32:24 2023 - ERROR - Failed to start tangd.socket service
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 60'
+ message='oe_test_high_nbde.sh line 60'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 60'
Wed Aug 30 02:32:24 2023 - ERROR - oe_test_high_nbde.sh line 60
+ return 0
+ SSH_CMD 'systemctl enable tangd.socket;mkdir /etc/systemd/system/tangd.socket.d'
+ cmd='systemctl enable tangd.socket;mkdir /etc/systemd/system/tangd.socket.d'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'systemctl enable tangd.socket;mkdir /etc/systemd/system/tangd.socket.d' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Wed Aug 30 02:32:24 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ P_SSH_CMD --node 2 --cmd 'echo -e [Socket]\\nListenStream=\\nListenStream=8009 > /etc/systemd/system/tangd.socket.d/override.conf'
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --node 2 --cmd 'echo -e [Socket]\\nListenStream=\\nListenStream=8009 > /etc/systemd/system/tangd.socket.d/override.conf'
Wed Aug 30 02:32:24 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ SSH_CMD 'systemctl daemon-reload;systemctl show tangd.socket -p Listen | grep 8009;
    		systemctl start tangd.socket;systemctl stop firewalld;setenforce 0'
+ cmd='systemctl daemon-reload;systemctl show tangd.socket -p Listen | grep 8009;
    		systemctl start tangd.socket;systemctl stop firewalld;setenforce 0'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'systemctl daemon-reload;systemctl show tangd.socket -p Listen | grep 8009;
    		systemctl start tangd.socket;systemctl stop firewalld;setenforce 0' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Wed Aug 30 02:32:24 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ curl http://127.0.0.1:8009/adv -o adv.jws
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 8009 after 0 ms: Couldn't connect to server
+ SLEEP_WAIT 1
+ wait_time=1
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 1 --cmd '' --mode 1
+ expect '-c
        set timeout 120
        spawn luksmeta init -n -d /dev/sr01
	expect {
		"yn" {
			send "y\r"
			exp_continue
		}
		timeout
	}
    '
spawn luksmeta init -n -d /dev/sr01
couldn't execute "luksmeta": no such file or directory
    while executing
"spawn luksmeta init -n -d /dev/sr01"
+ CHECK_RESULT 0 0 0 'luksmeta init failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='luksmeta init failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ echo
+ luksmeta save -d /dev/sr01 -s 0 -u f09f31c0-7ebb-4d87-884c-8af053b6425d
oe_test_high_nbde.sh: line 79: luksmeta: command not found
+ expect '-c
	set timeout 120
        spawn clevis luks bind -d /dev/sr01 sss '\''{"t":1,"pins":{"tang":[{"url":"http://127.0.0.1:8009"},{"url":"http://:8009"}]}}'\''
	    expect {
		"ynYN" {
			send "y\r"
			exp_continue
		}
		"yn" {
            send "y\r"
            exp_continue
            }
		"assword" {
            send "\r"
            exp_continue
        }
		timeout
	}
'
extra characters after close-brace
    while executing
"spawn clevis luks bind -d /dev/sr01 sss '{"t":1,"pins":{"tang":[{"url":"http://127.0.0.1:8009"},"
+ CHECK_RESULT 0 0 0 'Disk binding failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Disk binding failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ expect '-c
        set timeout 120
        spawn clevis luks unbind -d /dev/sr01 -s 1
	    expect {
		"yn" {
			send "y\r"
			exp_continue
		}
		timeout
	}
    '
spawn clevis luks unbind -d /dev/sr01 -s 1
couldn't execute "clevis": no such file or directory
    while executing
"spawn clevis luks unbind -d /dev/sr01 -s 1"
+ CHECK_RESULT 0 0 0 'Disk unbinding failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Disk unbinding failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Wed Aug 30 02:32:25 2023 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Aug 30 02:32:25 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Aug 30 02:32:25 2023 - INFO  - start environment cleanup.
+ umount /mnt/test_encrypted
umount: /mnt/test_encrypted: not mounted.
+ cryptsetup close test_encrypted
oe_test_high_nbde.sh: line 118: cryptsetup: command not found
+ mkfs.ext4 /dev/sr01 -F
mke2fs 1.47.0 (5-Feb-2023)
The file /dev/sr01 does not exist and no size was specified.
+ echo -e 'd\n\nw'
+ fdisk /dev/sr0
fdisk: cannot open /dev/sr0: No medium found

Welcome to fdisk (util-linux 2.39.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Wed Aug 30 02:32:25 2023 - WARN  - no thing to do.
+ return 0
+ rm -rf secert.jwe adv.jws sec.jwe input-plain.txt /etc/systemd/system/tangd.socket.d /mnt/test_encrypted1 /var/db/tang /tmp/header.bin
+ DNF_REMOVE 2 tang
+ node=2
+ pkg_list=tang
+ mode=0
+ [[ -z '' ]]
+ [[ -z tang ]]
+ '[' 0 -ne 0 ']'
+ '[' 2 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 2 --pkgs tang --tempfile ''
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 142, in rpm_remove
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ '[' 0 -ne 0 ']'
+ SSH_CMD 'rm -rf /etc/systemd/system/tangd.socket.d /var/db/tang'
+ cmd='rm -rf /etc/systemd/system/tangd.socket.d /var/db/tang'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'rm -rf /etc/systemd/system/tangd.socket.d /var/db/tang' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Wed Aug 30 02:32:25 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ mkfs.ext4 /dev/sr0 -F
mke2fs 1.47.0 (5-Feb-2023)
mkfs.ext4: No medium found while trying to determine filesystem size
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Aug 30 02:32:25 2023 - INFO  - Finish environment cleanup!
