+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Sep  1 15:22:16 2023 - INFO  - Start to prepare the database config.
++ date +%Y%m%d%H%M%S
+ cur_date=20230901152216
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20230901152216
+++ lsblk
+++ grep disk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vda
++ disk_name=/dev/vda
++ pvcreate /dev/vda -f
++ [[ 5 -eq 0 ]]
+++ pvcreate /dev/vda
+++ grep test_vggroup
+++ cut -d '"' -f 4
++ vggroup=
++ printf
printf: usage: printf [-v var] format [arguments]
+ vggroup=
+ lv=test_lv20230901152216
+ lvcreate -n test_lv20230901152216 -L 2G -y
  No command with matching syntax recognised.  Run 'lvcreate --help' for more information.
  Nearest similar command has syntax:
+ mkfs.ext3 /dev//test_lv20230901152216
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv20230901152216 does not exist and no size was specified.
+ testPoint=/mnt/test20230901152216
+ mkdir /mnt/test20230901152216
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Fri Sep  1 15:22:17 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Sep  1 15:22:17 2023 - INFO  - Start to run test.
+ mount -t ext3 /dev//test_lv20230901152216 /mnt/test20230901152216
mount: /mnt/test20230901152216: special device /dev//test_lv20230901152216 does not exist.
       dmesg(1) may have more information after failed mount system call.
+ echo 'test ext3 fs'
+ umount /mnt/test20230901152216
umount: /mnt/test20230901152216: not mounted.
+ tune2fs -O extents,uninit_bg,dir_index /dev//test_lv20230901152216
tune2fs: No such file or directory while trying to open /dev//test_lv20230901152216
Couldn't find valid filesystem superblock.
tune2fs 1.47.0 (5-Feb-2023)
+ CHECK_RESULT 1 0 0 'Umount ext3 failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Umount ext3 failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Umount ext3 failed.'
+ LOG_ERROR 'Umount ext3 failed.'
+ message='Umount ext3 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Umount ext3 failed.'
Fri Sep  1 15:22:18 2023 - ERROR - Umount ext3 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_ext3_to_ext4.sh line 39'
+ message='oe_test_FSIO_mount_ext3_to_ext4.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_ext3_to_ext4.sh line 39'
Fri Sep  1 15:22:18 2023 - ERROR - oe_test_FSIO_mount_ext3_to_ext4.sh line 39
+ return 0
+ fsck -pf /dev//test_lv20230901152216
fsck from util-linux 2.39.1
fsck.ext2: No such file or directory while trying to open /dev//test_lv20230901152216
Possibly non-existent device?
+ mount -t ext4 /dev//test_lv20230901152216 /mnt/test20230901152216
mount: /mnt/test20230901152216: special device /dev//test_lv20230901152216 does not exist.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32 0 0 'mount ext4 failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='mount ext4 failed.'
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'mount ext4 failed.'
+ LOG_ERROR 'mount ext4 failed.'
+ message='mount ext4 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'mount ext4 failed.'
Fri Sep  1 15:22:19 2023 - ERROR - mount ext4 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_ext3_to_ext4.sh line 42'
+ message='oe_test_FSIO_mount_ext3_to_ext4.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_ext3_to_ext4.sh line 42'
Fri Sep  1 15:22:19 2023 - ERROR - oe_test_FSIO_mount_ext3_to_ext4.sh line 42
+ return 0
+ grep test /mnt/test20230901152216/testFile
test ext3 fs
+ CHECK_RESULT 0 0 0 'Transfer ext3 to ext4 failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Transfer ext3 to ext4 failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Sep  1 15:22:19 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep  1 15:22:20 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Sep  1 15:22:20 2023 - INFO  - Start to restore the test environment.
+ REMOVE_FS /mnt/test20230901152216
+ point_list=($1)
++ seq 0 0
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/mnt/test20230901152216
++ df -T
++ grep /mnt/test20230901152216
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Sep  1 15:22:21 2023 - INFO  - End to restore the test environment.
